### ISSUE TITLE
Tests are flaky / failing

### ISSUE THREAD

**Issue by tomliversidge** [AsynkronIT/protoactor-dotnet#153] opened 2017-04-10 10:13 UTC
https://ci.appveyor.com/project/protoactor-ci/protoactor-dotnet/build/dev-199/tests
https://ci.appveyor.com/project/protoactor-ci/protoactor-dotnet/build/process-redesign-195/tests
https://ci.appveyor.com/project/protoactor-ci/protoactor-dotnet/build/dev-190/tests

etc...

**Comment by alexpantyukhin** [comment] 2017-04-21 13:14
@tomliversidge  Is it still reproducing?

**Comment by tomliversidge** [comment] 2017-04-21 18:18
Hmmm... not sure. We've had a few failures in the last week on the build server, but I'm not sure if they are about mailbox issues

**Comment by rogeralsing** [comment] 2017-04-22 13:31
Agree, there seems to be random failures going on in the buildserver.
I guess it's the usual non deterministic stuff, slow server, unfair scheduler, tasks are timing out

**Comment by cpx86** [comment] 2017-04-22 13:42
The Mailbox tests fail because we use `Task.ContinueWith` which will asynchronously schedule the continuation task. If we could inject a synchronous `TaskScheduler` (perhaps via the `IDispatcher` interface) then we should be able to get rid of the time-dependence and `Thread.Sleep`.

**Comment by tomliversidge** [comment] 2017-05-18 09:10
I _think_ I've been able to remove some of the Thread.Sleeps in the mailbox tests by Wait()-ing in the IDispatcher in TestMailboxHandler.cs:

```
public void Schedule(Func<Task> runner)
        {
            runner().Wait();
        }
```

This is what we do in TestDispatcher.cs already

**Comment by masteryee** [comment] 2017-09-20 02:52
Several builds have passed successfully with no test failures after the merge. Please close this issue.

**Closed** 2017-09-20 03:28 UTC
Labels: bug
