### ISSUE TITLE
Is it possible to add callback to the pid.Tell/context.Send?

### ISSUE THREAD

**Issue by kokizzu** [AsynkronIT/protoactor-dotnet#479] opened 2019-08-19 17:26 UTC
So I can process the response on the same scope of the sender/caller.
```
pid.Tell(message, delegate {
  // oncomplete
});
```
or in Go:
```
context.Send(pid, message, func() {
 // oncomplete
})
```

the problem I was facing was, I'm using Unity3D on the caller/client, and Go on the server side. From the server side I can't contact the client if they doesn't use real IP, which leads to few solution:
1. whether callback exists
2. create my own proxy using other protocol (TCP or others) which have 2nd Actor that receive the response of the 1st Actor and send back to the client

**Comment by sudsy** [comment] 2019-08-20 00:54
I encountered a similar problem with one of my use cases.

I have done some work #444 on a project that allows connection to the protoserver without needing the protoserver to open a connection back to the client.

I have been running it in production for several months but have plans for a breaking refactor before I release it.

Using this method the client can receive messages from the server or the client can make a context.RequestAsync call to the server and receive the response within the original context (like your callback example above).

You would need to build [My proto_client branch](https://github.com/sudsy/protoactor-dotnet/commits/proto_client) and deploy it into your project using a [local nuget repository](https://medium.com/@churi.vibhav/creating-and-using-a-local-nuget-package-repository-9f19475d6af8) too.

**Comment by kokizzu** [comment] 2019-08-20 03:00
I wrote my own C# TCP client and Go TCP server yesterday XD

**Comment by alexeyzimarev** [comment] 2020-06-08 10:49
I think it would make sense to change the request/response flow in case of using the client without  server->client direct connection. Doing so will be semantically correct, comparing with callbacks for `Send`, because `Send` is essentially fire and forget.

**Comment by rogeralsing** [comment] 2020-09-06 09:51
Duplicate of https://github.com/AsynkronIT/protoactor-dotnet/issues/444

**Closed as completed by rogeralsing** 2020-09-06 09:51 UTC
