### ISSUE TITLE
Is this dead? Who is using it in production?

### ISSUE THREAD

**Issue by SixFootRhino** [AsynkronIT/protoactor-dotnet#461] opened 2019-04-19 18:30 UTC
Is the .Net version of Proto.Actor dead? The reason I ask:

* Gitter chat goes unresponded.
* An issue opened here almost a month ago goes unresponded.
* No commits in months.
* Large swaths of documentation pages are skeletons. 
* 0 Releases

Orleans community seems vibrant in comparison, but it's also very "heavy" compared to Proto.Net.

Akka is out of the question for us,a s the system screams for virtual actors. I've have a Love-Hate relationship with Service Fabric: I love to hate it. ;-)

I plan on evaluating both Proto.Net and Orleans, but if this is dead and none of the original contributors are planning on coming back to it, I'll probably bail...

**Comment by jrouaix** [comment] 2019-04-23 11:04
Hello @SixFootRhino, I'm not the core maintainer/creator of protoactor-dotnet but I use it in production.
I share your concerns, ProtoActor is a pretty interesting alternative compared to Orleans and Akka but it lack a strong community. 

I can share  you some of our work done on top off ProtoActor (reminders with rabbitmq for example) that I didn't open source for now.

We did also some service fabric, and we are now trying to get rid of it.

The https://github.com/vlingo-net project is rising, but it's still in very early stages, and probably the community is as little as proto actor.

**Comment by conejo** [comment] 2019-04-23 19:42
The protoactor-go project has some recent activity, so that's good to see. I am concerned seeing this project stagnate, I have a couple projects using it and really enjoy using it. It's been rock solid for us a little less than a year.

**Comment by ehouarn-perret** [comment] 2019-04-24 15:25
> Is the .Net version of Proto.Actor dead? The reason I ask:
> 
> * Gitter chat goes unresponded.
> * An issue opened here almost a month ago goes unresponded.
> * No commits in months.
> * Large swaths of documentation pages are skeletons.
> * 0 Releases
> 
> Orleans community seems vibrant in comparison, but it's also very "heavy" compared to Proto.Net.
> 
> Akka is out of the question for us,a s the system screams for virtual actors. I've have a Love-Hate relationship with Service Fabric: I love to hate it. ;-)
> 
> I plan on evaluating both Proto.Net and Orleans, but if this is dead and none of the original contributors are planning on coming back to it, I'll probably bail...

I feel you, I am starting to work on a new project from scratch and thought going for Protoactor but sadly the lack of activity kinda scares me.

Any reason why you folks decided not to go for alternative (eg. Orleans, Akka)?

**Comment by ehouarn-perret** [comment] 2019-04-24 15:29
> Hello @SixFootRhino, I'm not the core maintainer/creator of protoactor-dotnet but I use it in production.
> I share your concerns, ProtoActor is a pretty interesting alternative compared to Orleans and Akka but it lack a strong community.
> 
> I can share you some of our work done on top off ProtoActor (reminders with rabbitmq for example) that I didn't open source for now.
> 
> We did also some service fabric, and we are now trying to get rid of it.
> 
> The https://github.com/vlingo-net project is rising, but it's still in very early stages, and probably the community is as little as proto actor.

That would be awesome if folks like you could share a bit of their work with protoactor to fill the gap with the documentation or lack of thereof.

**Comment by SixFootRhino** [comment] 2019-04-24 16:43
> I feel you, I am starting to work on a new project from scratch and thought going for Protoactor but sadly the lack of activity kinda scares me.

Glad to see I'm not the only one. ;-)

> Any reason why you folks decided not to go for alternative (eg. Orleans, Akka)?

We are actually going to prototype Oreans. It really came down to that or Proto.Actor.

We're not considering Akka because virtual actors are a perfect fit for most of the services in this project. ClusterSharding in Akka is close but not really the same thing. Orleans or the Virtual Actors in Proto.Actor are simply a much better fit.

However, in theory Proto.Actor would have been a great fit as well, and in the past it has had significant performance advantage over Orleans. However, recent additions to Orleans 2.0 and 2.1 has saw some substantial performance improvements due to the work of the community. The fact that there even is a solid community behind it making these types of improvements certainly adds to it's appeal....

Furthermore, Orleans has had Journaled virtual actors for quite some time now, as well as a modern agent-based Distributed Transaction support that was recently added. These features will greatly reduce the difficulty in meeting the requirements in our project. Not all of our grains will fit the journaled model, but those which do will be able to provide a much simpler consistency implementation at scale.

While on the subject, does anybody know of an established virtual actor framework for .Net / C# that I'm overlooking?

> The https://github.com/vlingo-net project is rising, but it's still in very early stages, and probably the community is as little as proto actor.

vlingo looks interesting, but as pointed out is way too early. Plus, it seems to suffer a bit from NIHS: Not Invented Here Syndrome. Look at all of the sub-projects. There are established projects out there for most of these. For example, why would you build a HTTP/S server for vlingo when Kestrel is a thing?

**Comment by adamhathcock** [comment] 2019-04-24 17:20
I wouldn’t say this is dead but it’s lacking vision as the primary devs (and myself) have interests elsewhere now I guess.

Are there features or bugs?  Make issues or PRs.  I’m sure if other people are active enough, they can have control over the repo.

**Comment by PotterDai** [comment] 2019-04-24 17:44
Hi guys, thank you for the post!

I jumped onto ProtoActor when I was doing my previous project, and I mainly
contributed to the Cluster part of the project, as well as bridging dotnet
version with go version all together. Unfortunately my current project is
not using ProtoActor, thus I’m currently more focus on maintaining the
project, fixing bugs and answering issues. I guess Roger is same as well? I
hope I can jump back onto this project again after my current project. = )

Same as you, I was choosing between Orleans and ProtoActor since that’s the
only two libraries available at that time. And for protoactor-go, I think
till today it is still the most mature Actor library for Golang.

I ended up choosing ProtoActor because:
For Orleans: it’s solid but very heavy. We need to re-establish our entire
project structure based on it. It also got its own messaging system,
serialization, cluster structure, etc., which is a Good/Bad thing from
different point of view.
For ProtoActor:  it’s lightweight and flexible. It can be used alongside
with any existing libraries, without changing much of existing code
structure, and it uses Consul and GRPC which is very mature and performant.

And for us we need something quick to integrate, and fast(or even hacky) to
build, so we in the end choosing ProtoActor.

In the end I think it’s more of a design choise. The diffence between the 2
projects are written in Roger’s blog:
https://rogerjohansson.blog/2017/05/19/do-not-do-in-code-what-can-be-done-in-infrastructure/

**Comment by alexeyzimarev** [comment] 2019-04-24 17:53
We use Proto.Actor in production and we process about 5 billions of messages per month., per "service", which we have two. The documentation is definitely lacking and I still have plans to improve it but I have a couple of tough deadlines now, so will not start until the end of May. At the same time, Proto.Actor just works. I have tried Orleans and it was just no-go. I don't want to say anything bad abut Orleans but they _must_ be working really hard to clean up all that mess that they have created previously. Luckily, Proto.Actor doesn't have such a legacy. I would say that things that bother me the most are:
- no releases after some nasty bugs were fixed
- docos
- issues with Consul cluster provider
We keep our local copy of the code and although I am now a member of the org here, I am not feeling very comfortable doing things without having a discussion with core contributors, but they apparently have even less time than me. But definitely, we need to do at least a new release.

As for the features, it would be nice to do a proper version of streams. Orleans streams have nice ideas and somewhat convoluted implementation and Akka streams a quite weird. I have some ideas but it's quite a lot of work.

And, of course, if you guys think that the project is useful and you want to use it in prod - it is a library and you can read its code in a couple of hours (unlike Akka or Orleans), open issues if you get any, fix issues. The only way OSS projects live is that people contribute and don't scream "is it dead??". Sorry if it's a bit harsh, but I've heard this so much in RestSharp...

**Comment by PotterDai** [comment] 2019-04-24 18:07
@alexeyzimarev Agree, I actually never realized that OSS projects took so much efforts until I became part of the ProtoActor's team, haha.
Similar to you, I certainly love to push a new release, but not feeling very comfortable to do so since I believe @rogeralsing should be the guy to make the final push? However from certain point @rogeralsing just disappeared.

**Comment by SixFootRhino** [comment] 2019-04-24 18:22
Thanks for both of your replies.

The #1 concern I have with Orleans is it's heft and inflexibility of the model. While they have done a good job in embracing the provider pattern, there is a still a lot of rigidity to do things their way. I do concur that Proto.Actor does seem far more flexible in this regard, and definitely more lightweight.

The #1 concern I have with Proto.Actor is exactly what you said:

"no releases after some nasty bugs were fixed"

Maybe I'm missing something, but there's been no releases, right?

That scares me. If not Roger, somebody needs to take the reins so that critical fixes to nasty bugs are submitted and make it into at least one stable release that people can grab. If they aren't, people will be scared away, and there will be no adoption and community growth.

Are all of these "nasty bug" fixes in as closed pull requests? Or do people still have them in their own copy of the library only?

**Comment by PotterDai** [comment] 2019-04-24 18:29
@SixFootRhino To answer your last question, In our use case we just use latest version from MyGet instead of a released version from Nuget. I know it's hacky but it just works. 
This has never been a problem in Go since it's always fetches the latest.

**Comment by alexeyzimarev** [comment] 2019-04-24 18:34
As I wrote, we build from source and we fix things so when we ensure our fixes work, we can bring it back here. The repo is not huge and you don't usually need all of it. MyGet works also like @PotterDai mentioned. I agree that we need to make a release of a minor with bug fixes, then merge #452 and #455 and make a major.

**Comment by rogeralsing** [comment] 2019-04-25 12:45
Some clarifications from my side:

### Design concepts behind Proto.Actor

Proto.Actor was designed from day 1 to be narrow in scope.
Meaning that we did not want to have a never ending project like Akka .NET was.

Instead we aimed for solving the key issues about scaling, concurrency etc.

As such, much of the project was "done" long ago in terms of key features, where any new commits have mostly been about bug fixes, updating the API based on feedback/new lessons learned etc.
e.g. Stablising the Cluster support

### On a personal level

For me personally, I do not have a lot of time for OSS work anymore, mostly work and family right now.

### Philosophical level

I've also changed my stance somewhat on the topic of Actor frameworks.
I still love the concept. but in the current state of where cloud computing is moving.
There are often better options.

e.g. leveraging PaaS services of Azure or AWS takes you _really really_ far.

For example, Lambda/Azure functions are extremely cheap and easy to build, and scale.

Azure event hubs gives built in support to raise events through your systems.

This leaves a more or less niched area for actors, e.g high performance processing. fin tech etc, iGaming etc.

But fault tolerant clusters or event driven systems can pretty much be done with out of the box offerings without the hassle of running custom software clusters.

### Moving forward

We have been discussing things interanlly about moving Proto.Actor to some form of foundation. but this has been hard as we have C#, Go and Kotlin implementations.
There is no clear polyglot foundation where this might fit.

Any ideas there would be welcome.

**Comment by SixFootRhino** [comment] 2019-04-25 15:04
> I agree that we need to make a release of a minor with bug fixes, then merge #452 and #455 and make a major.

This would be fantastic @alexeyzimarev, but as has been noted I'll just get head and build local as it sounds like all of the critical fixes are in the codebase.

@rogeralsing thanks for the candid response. I also agree for a lot of systems, Azure and AWS have so many great pieces now that you should approach every system design with the idea that you will use them, and only move away when it's absolutely necessary.

Gaming (my field) is one area where this has been slow to adopt PaaS for certain titles, and will remain to be for the foreseeable future unless Streaming takes off. 

I absolutely concur that for the time being anyway, there'll be a strong need for tech like Akka or Proto.Actor or Orleans, or even non-actor frameworks, for building massively scalable games. The fact is for the biggest games, they don't rely on just one cloud provider. Some games deploy to 50+ PoP's across a half-dozen providers, including the big 3. When you do that, you can't rely on any one PaaS. You have to, unfortunately, have built your own that has enough abstraction so that it doesn't care where it runs. As awesome as pieces like EventHub and GameLift are, they tie you to one provider. Fine for most systems and industries, and even fine for many games, but not fine for all games.

> Any ideas there would be welcome.

Unfortunately I don't have any suggestions where Proto.Actor would end up wrt foundations; not my strong suit.

However, I have decided that I'm going to build the prototype slice for my next title in both Orleans and Proto.Actor so that I can get a better feel for both. Having just come off a large-ish Service Fabric project (with over 50 services), I'm definitely open to the idea of something lighter weight and more flexible.

**Comment by sudsy** [comment] 2019-04-26 03:33
@rogeralsing IT's PaaS services like Lambda that have lead me to ProtoActor

The use of protobuf and GRPC is perfect for an environment where you need to coordinate the work of many different Lambda functions. 

Conceptually, I am using protoactor-dotnet where each Lambda is like a short lived actor that can communicate back to the central cluster. 

We had been using Orleans for several years in a similar way but had to build an integration layer between the lambdas and Orleans. Keeping grain definitions up to date between the processes on the lambdas was a nightmare that is no longer due to the use of protobuf and grpc in protoactor.

The whole thing is much easier to program and reason about because my lambda clients are essentially just other actors programmed in the same way as the ones that reside in the server. In orleans you need to adopt a different mindset for the clients.

Anyway, we have been using it in production for about a month, but with thousands of lambda processes connecting and disconnecting as our (extremely variable) load changes. So far I am extremely happy and hope to make some bug fix and feature contributions back to the project shortly.

For the time being I just build from source into a local folder nuget repository. As far as I am concerned, the work I did to get my project up and running on ProtoActor has been far less than what I would have needed on Orleans and I feel much more comfortable making changes to the code bases since it is much easier to get my head around.

**Comment by rogeralsing** [comment] 2019-04-27 09:04
So what can we do to keep thing rolling?

We have a fairly well defined scope for the project, what to aim for design-wise.

Any participants here want commit rights?

**Comment by alexeyzimarev** [comment] 2019-04-27 10:09
I have commit rights and I plan to rewrite the Consul provider and possibly work on a Kubernetes provider. But I don't feel comfortable moving along without my code being reviewed. Also, we need some release strategy and a larger group needs to get access to both MyGet and NuGet feeds.

**Comment by sudsy** [comment] 2019-04-27 12:20
I have little time to spare like most people here, but I would be prepared to become a committer to review occasional pull requests. 

Is it the normal workflow that committers should submit their own changes as pull requests for other committers to review?

**Comment by Valentin-Miroshnichenko** [comment] 2019-04-28 07:14
Hi guys. I'm porting protoactor-dotnet to python. Maybe you could do code review and apply my [commits](https://github.com/AsynkronIT/protoactor-python/pull/49) to main branch of python version, or give me rights to python repository?

**Comment by PotterDai** [comment] 2019-04-28 07:49
@Valentin-Miroshnichenko Wow!! Didn't notice that since I'm not within protoactor-python's channel! That's a huge amount of progress! Thank you very much for the contribution! =D

**Comment by bjarteskogoy** [comment] 2019-05-28 13:35
Maybe you could try to get some love and attention from https://dotnetfoundation.org/about

**Comment by mzwaal** [comment] 2019-06-02 08:29
The Cloud Native Computing Foundation seems like a better place for this project because it is language/platform neutral: https://www.cncf.io/

**Comment by kiwill** [comment] 2019-07-03 07:49
> @SixFootRhino To answer your last question, In our use case we just use latest version from MyGet instead of the released version from Nuget. I know it's hacky but it just works.
> This has never been a problem in ProtoActor-Go since it's always fetches the latest.

@PotterDai Hi Potter. How can I fetch the latest version of protoactor-dotnet and protoactor-go from MyGet? What's the feed url?

**Comment by PotterDai** [comment] 2019-07-03 19:56
Hi @kiwill , you can find the latest protoactor-dotnet from MyGet using following feed:
https://www.myget.org/F/protoactor/api/v3/index.json
For protoactor-go, I think it automatically update to the latest branch! = )

**Comment by kiwill** [comment] 2019-07-04 01:12
thanks! @PotterDai

**Comment by alexeyzimarev** [comment] 2020-03-05 20:31
@AsynkronIT/developers I perfectly understand that you guys are quite busy. At the same time, I'd like to get some clarity on how to move forward. I have two large PRs open now. One is to update a long list of obsolete packages and move to .NET Standard 2.0 solely. Another one is to fix old and nasty cluster recovery issues and Consol provider problems. My organisation active uses Proto.Actor and we have the will and the ability to develop it, but, despite being a maintainer here, I struggle to understand my role and the role of AsynkronIT. 

Do you want to keep the ownership and the copyright of Proto.Actor or you plan to separate it to its own, community-driven GitHub org?

Do you plan to do code reviews still?

Can I just merge my PRs and other pending PRs? 

Who will be releasing NuGet packages to nuget.org?

What to do with the website? It's really outdated and even the generator used there is not being maintained anymore.

I have even more questions, but I have no idea how to reach out and have a discussion.

**Comment by rogeralsing** [comment] 2020-03-07 10:42
@PotterDai send me your nuget name an I can add you to the nuget org.

Things that could use some love right now:

* New site generator
* New build pipeline + Nuget publishing pipeline

**Comment by rogeralsing** [comment] 2020-03-07 10:43
Also, anyone who needs commit rights, let me know.

**Comment by sudsy** [comment] 2020-03-07 11:13
I would like commit rights please.

**Comment by rogeralsing** [comment] 2020-03-07 11:42
@sudsy done!

I've removed the last traces of .NET 461.
Also merged the TestKit from @Vindil 

The TestKit is similar to testkit in Akka, we should review the design of it to polish it of, and then look into where it makes sense to use the testkit for the other tests in the solution.

**Comment by rogeralsing** [comment] 2020-03-07 18:56
Been away from .NET for some time, whats the status on C# 8 and Netstandard 2?
Is it possible to use C# 8 and still be backwards compat?

**Comment by alexeyzimarev** [comment] 2020-03-07 18:58
Yeah, using C# 8 is possible since .NET Core SDK 2.1. It's the compiler who applies restrictions, so newer SDKs can build for older versions from the source code written with the latest lang version.

**Comment by rogeralsing** [comment] 2020-03-07 19:29
And down the rabbit hole with nullability now :)

**Comment by alexeyzimarev** [comment] 2020-03-07 19:30
Yeah, that's a bit mad. I'd very much like have a more powerful type system like Rust, instead of trying to save nullable types from misery.

**Comment by alexeyzimarev** [comment] 2020-03-07 23:45
@rogeralsing I saw you trying the nullability thing. I spent a bit of time resolving issues with the `Proto.Actor` project but some places weren't possible to fix. For example, the `TrySetResult` call where null is possible but `TrySetResult` doesn't have it nullable. Also, `PID` is a partial class, a part of it is generated and we have no control over it, but the compiler complains. When I got enough pragmas around those places, I asked myself if it's necessary...

**Comment by alexeyzimarev** [comment] 2020-03-11 21:41
> * New build pipeline + Nuget publishing pipeline

That's done now

**Comment by alexeyzimarev** [comment] 2020-03-12 14:30
So, new packages get to nuget.org now, no need to look at MyGet anymore.

https://www.nuget.org/packages/Proto.Actor/0.2.1-alpha.0.15

the first package since 0.2.0 🎉

**Comment by Johnny-Bee** [comment] 2020-03-12 15:17
Great Job @alexeyzimarev ! Thank you very much!

**Comment by Swoorup** [comment] 2020-03-15 22:44
Anybody still using this in production?

**Comment by alexeyzimarev** [comment] 2020-03-16 09:04
@Swoorup not sure where you got this impression from, I believe the whole discussion in this issue shows the opposite.

I think there's no need to keep this issue open.

**Closed by alexeyzimarev** 2020-03-16 09:04 UTC

**Comment by Swoorup** [comment] 2020-03-24 09:41
@alexeyzimarev I looked at the insights, there wasn't much activity for 2 years until few months ago. In case any I am glad to be proven wrong. ;)
