### ISSUE TITLE
Duplicate message types after explicit call of Cluster.WithProtoMessages

### ISSUE THREAD

**Issue by artemiusgreat** [AsynkronIT/protoactor-dotnet#1148] opened 2021-08-27 07:20 UTC
## Expected Behavior
To start cluster. 

## Actual Behavior
Extension method `WithProtoMessages` is being called with parameters (messages) that were already added to `TypeLookup` variable. 

```
System.ArgumentException: 'An item with the same key has already been added. Key: actor.PID'
This exception was originally thrown at this call stack:
System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException<T>(T)
System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey, TValue, System.Collections.Generic.InsertionBehavior)
System.Collections.Generic.Dictionary<TKey, TValue>.Add(TKey, TValue)
Proto.Remote.Serialization.RegisterFileDescriptor(Google.Protobuf.Reflection.FileDescriptor) in Serialization.cs
Proto.Remote.RemoteConfigExtensions.WithProtoMessages<TRemoteConfig>(TRemoteConfig, Google.Protobuf.Reflection.FileDescriptor[]) in RemoteConfigExtensions.cs
EventStreamTopicsCluster.Program.Main() in Program.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

If I try to comment the call of `WithProtoMessages`, I get another error. 

```
System.Net.Http.HttpRequestException: 'No such host is known. (consul:8500)'
This exception was originally thrown at this call stack:
System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)
System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(short)
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
System.Net.Sockets.Socket.ConnectAsync.__WaitForConnectWithCancellation|283_0(System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs, System.Threading.Tasks.ValueTask, System.Threading.CancellationToken)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
System.Net.Http.HttpConnectionPool.DefaultConnectAsync(System.Net.Http.SocketsHttpConnectionContext, System.Threading.CancellationToken)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

## Steps to Reproduce the Problem

  1. Visual Studio 2022 version 17 Preview 3 
  2. Start consul in docker `docker run -p 8500:8500 --name=consul consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0`
  3. Run this [sample](https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/examples/EventStreamTopicsCluster) 
 
## Specifications

  - Version: .NET 5.0 with latest `dev` branch
  - Platform: Windows 10 Pro x64

**Comment by artemiusgreat** [comment] 2021-08-27 07:24
Is it intentional that `TypeLookup` is being initialized using `Add` method instead of assigning values to keys directly? 
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Remote/Serialization/Serialization.cs#L83 

Why 
```
TypeLookup.Add(msg.FullName, msg.Parser);
```
Instead of 
```
TypeLookup[msg.FullName] = msg.Parser;
```

**Comment by rogeralsing** [comment] 2021-08-27 07:36
I'm probably missing context here. but what is the reason for adding the same message definition multiple times here?
Is the issue that you want a better error message, or is there something else you are trying to do here?

**Comment by artemiusgreat** [comment] 2021-08-27 08:30
This is not my sample, so I'm not sure why message definition was added multiple times, I'm just running an example from this repo :) 
Meanwhile, the exception happens because message definition is added at least twice, this is a part of the question. 

I see that method `Serialization.RegisterFileDescriptor` is being executed twice, one time in the Serialization constructor, second time in the `WithProtoMessages` in the code sample from this repo when cluster is being created.
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Remote/Serialization/Serialization.cs#L44 
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Remote/RemoteConfigExtensions.cs#L81

In general, I'm just trying to run any code sample demonstrating cluster, specifically the one below. 
https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/examples/EventStreamTopicsCluster

**Comment by artemiusgreat** [comment] 2021-08-27 08:37
Actually, I just checked another sample and it seems to work fine. 
https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/examples/ClusterPubSub 
Maybe because PubSubCluster sample defines messages only in the current namespace. 
```
WithProtoMessages(ClusterPubSub.ProtosReflection.Descriptor)
```
Menwhile, EventStreamCluster seems to try to get all messages it can find. 
```
WithProtoMessages(Proto.ProtosReflection.Descriptor)
```

**Comment by artemiusgreat** [comment] 2021-08-27 10:00
I think, the method call to `WithProtoMessages` is not needed in the EventStreamCluster example because this sample doesn't have `*.proto` files. The only message type it has is defined in C#. 

For some reason cluster can't deserialize message types defined in C#. If I define [proto message](https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/examples/ClusterPubSub/protos.proto) as C# class. 

```
[Serializable]
public class SomeMessage
{
    public int Value { get; private set; }

    /*
    public SomeMessage() {}
    */

    public SomeMessage(int value)
    {
        Value = value;
    }
}
```

I get an error.

```
fail: Proto.Remote.EndpointReader[0]
[EndpointReader] Unable to deserialize message with cluster.pubsub.ProducerBatch from ipv4:127.0.0.1:59842

warn: Proto.Cluster.DefaultClusterContext[0]
RequestAsync retried but failed for topic/my-topic, elapsed 00:00:05.6453800
```

@rogeralsing 

To reprase initial issue, is there any code sample showing how to use C# message classes with cluster or can C# class be used as a message in a cluster? Do I still need to register message type if it's defined in C#. If yes, how?

**Comment by artemiusgreat** [comment] 2021-08-28 14:23
This line is failing. 
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Remote/Endpoints/EndpointReader.cs#L130 

![image](https://user-images.githubusercontent.com/5140879/131221115-2b4cf8ba-5291-44c7-8e28-171f05b3d1c3.png)

Then, this one.
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Remote/Serialization/ProtobufSerializer.cs#L26

![image](https://user-images.githubusercontent.com/5140879/131221577-0dd62653-fbcc-4f1d-add4-afa33db9eeb3.png)

I guess, every message needs to be registered in the `ActorSystem` and at the moment there is no way to register C# POCO classes.

**Comment by rogeralsing** [comment] 2021-08-28 16:46
@artemiusgreat sorry for the delayed answer.
I'm updating this example right now, it looks like this one was never fully completed for some reason.

Will link it once merged

**Comment by rogeralsing** [comment] 2021-08-28 17:18
Updated example here
https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/examples/EventStreamTopicsCluster

Also released 0.22.0 to allow cluster members to await seeing themselves during StartMemberAsync to make broadcasting behave correctly.

**Closed as completed by rogeralsing** 2021-08-28 17:18 UTC

**Comment by artemiusgreat** [comment] 2021-08-28 20:59
@rogeralsing Why was this closed? The issue here is not replacing C# POCO class with `proto` messages. The real issue is that `Proto.Remote` and `Proto.Cluster` don't expose any method to register messages defined in C# in the serializer. 

In other words, how to make cluster work without `messages.proto` files?

**Comment by rogeralsing** [comment] 2021-08-29 07:56
This issue is a mix of a bit of everything. the original question regarding duplicate keys is resolved.

1. Duplicate message types after explicit call of Cluster.WithProtoMessages

This was caused by the example incorrectly registering the standard Proto.Actor protobuf definitions.
Causing the duplicate key issue

2. don't expose any method to register messages defined in C# in the serializer.

That is not needed, we have a fallback to System.Text.Json for plain poco classes/records.

So why did it fail in your case? see 3:

3. [EndpointReader] Unable to deserialize message with cluster.pubsub.ProducerBatch 

This is due to the **Cluster.PubSub** feature in its current form can only handle Protobuf messages.
Cluster.PubSub is a different feature than the Cluster EventStream example.

We have big plans for Cluster.PubSub, e.g. adding durable messaging using external tools such as Kafka or RabbitMQ.
But since this will involve more things than just Proto.Actor itself. we need to plan for how this should work, e.g. in terms of serialization and message schemas.
